import { useState } from 'react';
import { authenticatedPost } from '@/lib/utils/api';

export function useTicketAutoGeneration() {
  const [isGenerating, setIsGenerating] = useState(false);

  const triggerAutoGeneration = async (ticketId: string) => {
    if (isGenerating) return;

    try {
      setIsGenerating(true);
      console.log('🤖 Triggering auto-generation for ticket:', ticketId);

      // Llamar API con flag autoGenerated
      const response = await authenticatedPost(`/api/tickets/${ticketId}/generate-pdf`, {
        autoGenerated: true
      });

      if (response.ok) {
        const result = await response.json();
        console.log('✅ Auto-generation successful:', result);
        return result;
      } else {
        const error = await response.json();
        console.error('❌ Auto-generation failed:', error);
        throw new Error(error.error || 'Failed to auto-generate PDF');
      }

    } catch (error) {
      console.error('❌ Error in auto-generation:', error);
      // No lanzar error - la auto-generación es silenciosa
      return null;
    } finally {
      setIsGenerating(false);
    }
  };

  return {
    triggerAutoGeneration,
    isGenerating
  };
}
